
/*
 * generated by Xtext
 */
 
package org.xtext.example.mydsl1.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.xtext.example.mydsl1.ui.internal.MyDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.xtext.example.mydsl1.ui.internal.MyDslActivator.getInstance().getInjector("org.xtext.example.mydsl1.MyDsl");
	}
	
}
