/*
* generated by Xtext
*/
package org.xtext.example.mydsl2.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class TestLanguageTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
