<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myDsl"
    nsURI="de.unisiegen.informatik.bs.alvis.language.algorithmLanguage" nsPrefix="myDsl">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//functionDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="main" eType="#//mainFunction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="functionDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formalParams" eType="#//formalParams"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mainFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formalParams" eType="#//formalParams"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="formalParams">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//param" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="param" eSuperTypes="#//statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="block" eSuperTypes="#//statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="type" eSuperTypes="#//param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//declaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="declaration" eSuperTypes="#//statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableType" upperBound="-1"
        eType="#//type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
